spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: 'update'
    open-in-view: false
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USER_NAME}
    password: ${EMAIL_PASSWORD}
    protocol: smtp
    properties:
      "[mail.smtp.auth]": ${SM_AUTH_ENABLE}
      "[mail.smtp.starttls]": ${SM_TTLS_ENABLE}
server:
  servlet:
    context-path: /api/v1/

application:
  security:
    email:
      activationUrl: ${EMAIL_SEND_ACTIVATION_TOKEN_URL}
      verification: ${SEND_EMAIL_VERIFICATION}
    jwt:
      secret: ${SECURITY_JWT_SECRET}
      expiration: ${SECURITY_JWT_EXPIRATION}
    activation-token:
      expiration: ${ACTIVATION_CODE_EXPIRATION_MINS}
      length: ${ACTIVATION_CODE_LENGTH}
      chars: ${ACTIVATION_CODE_CHARS}
    create-enabled-users: ${CREATE_ENABLED_USERS}
    allowed-origins: ${ALLOWED_ORIGINS}
    allowed-headers: ${ALLOWED_HEADERS}
    allowed-methods: ${ALLOWED_METHODS}
    request-matchers: ${REQUEST_MATCHERS}
    cors-configuration:
      pattern: "/**"
    csrf-enabled: false
  date:
    format: dd/MM/yyyy
  validation:
    email-regex: ${EMAIL_REGEX}